language: ruby

rvm:
  - "2.2.0"

sudo: false

before_install:
  - bundle config build.nokogiri --use-system-libraries

install:
  - travis_retry bundle install --jobs 4 --path vendor/bundle

script:
  - bundle exec rake spec

cache: "bundler"

deploy:
  provider: heroku
  api_key:
    secure: "RcUYYXOQryP4ikvpYskjviCBMxVdSezaGTH0bmfc04Y8L0c7FG5h4KRZ5jgQ+EsbUWjD2R8bhQEcsHk6PfXsMwp5p8ein9QIa5kvdK7yodTdtGA5/0R9g5112kg1hbPCZfrOheFpz7/lEFCAi8qROqd4CZiexMjhMusxRtUHsYs="   
  strategy: api
  app:
    master: cf-contest-check-334
    develop: test-cf-contest-check-334

